### ISSUE TITLE
SubQuery Support in Substrait

### ISSUE THREAD

**Issue by XinDongIntel** [substrait-io/substrait#123]
Subqueries are common in sql. Typically, it can appear in two forms.
1)In expression, for example,
SELECT * FROM lineitem WHERE orderkey IN (SELECT orderkey FROM orders WHERE (orderkey + custkey) % 2 = 0)
2)As part of from clause, such as
SELECT distinct orderkey FROM (SELECT orderkey FROM lineitem WHERE linenumber = 5)

For the subquery in expression, database engine usually use a special node type in expression tree (e.g. expSubQuery) to reprsent it.

For the subquery in from clause, database engine have two options to repesent it:
Option1: Introduce a subquery node (e.g. RelSubquery) in plan tree which points to the plan tree of the subquery.
Option2: Simply flattern the subquery plantree as the input of the main query. 

Should substrait also need representations for subquery?

**Comment by jacques-n** [comment]
Hey @XinDongIntel , completely agree. I actually opened #119 recently so let's keep the discussion on that ticket. Thanks!
