### ISSUE TITLE
Clarify longer term governance structure?

### ISSUE THREAD

**Issue by emkornfield** [substrait-io/substrait#13]
This might be premature, but does it pay to clarify what the vision for longer term governance of this effort is?  (is the goal to incubate this in the ASF?)

**Comment by jacques-n** [comment]
I've opened a discussion about this on #16. @emkornfield would be great if you added key attributes you'd want to see or want to avoid.

**Comment by emkornfield** [comment]
Thanks I think you captured most of the concerns on the discussion.
