### ISSUE TITLE
How should we express pushdown filtering?

### ISSUE THREAD

**Issue by westonpace** [substrait-io/substrait#137]
The `ReadRel` has a filter property defined (in the markdown) as:

> A boolean Substrait expression that describes the filter of a iceberg dataset. TBD: define how field referencing works.

I assume this is intended for pushing filtering down into the read.  However, it isn't clear to me if it is expected that the consumer is able to fully satisfy the filter or not.  There are many cases where filters cannot be pushed down, and some of those cases won't be known at plan creation time.

For example, if the source files are CSV then no filter pushdown is possible.  If the source files are parquet but there are no column statistics or bloom filters enabled for a particular source file.

As a result, in Arrow, we typically define plans with both a pushdown filter and a filter node.  The pushdown filter is basically a best-effort hint.

Is this the same intent in Substrait?  Or, if a consumer can't satisfy the filter in the ReadRel, is it expected that the consumer will do the additional filtering in-memory?

**Comment by jacques-n** [comment]
The TBD part of the definition is whether the filter is defined based on the original schema of the data or the mask selection. We need to choose one.


For the optionality: hmmm...

The current intended model is that a filter expressed must be applied. In the past, for this kind of optionality, I've defined it inside the scan operator rather than a separate concept in the plan. This is because one doesn't want to reapply the filter in the case that you can be done as part of the read (or part of it can) since that would waste time/cycles. 

I suppose we could create something which changes filter behavior from `required` to `best effort`. That being said, I'm initially inclined to model as an internal concern of the read though, instead of something that is exposed. What do you think?

**Comment by westonpace** [comment]
Sorry for the delay in coming back to this.  I think leaving it a concern of the read operator initially is fine.  If there is ever a reason we need to delay the optional filtering we can add the complexity later (or just use hints)

**Comment by westonpace** [comment]
I'll create a PR to clarify the wording.

> The TBD part of the definition is whether the filter is defined based on the original schema of the data or the mask selection. We need to choose one.

My two cents would be to use the original schema.  The masked schema is defined as `the portions of the content that should be read`.  The purpose of having a pushdown filter is that sometimes we can filter contents without reading them.  So it seems natural we'd be able to filter on contents that are not read.

**Comment by jacques-n** [comment]
Sounds good. Makes sense to me.

**Comment by curino** [comment]
Hi Folks, just getting started to understand substrait (apologies for dumb questions for a while). Do I read the above thread correctly that you are suggesting to have a `required` default behavior and express a `best effort` equivalent directly in the read operator? I think both behaviors can be of interest and if we can achieve the without extra explicit switches is great. One example were `best effort` is interesting is in scenarios where accelerators exist only for cached data (i.e., the same plan may or may not be executed by something that can handle filter pushdown).

**Comment by jacques-n** [comment]
For the filtering behavior, my proposal was to only support required initially (and support a best effort flag later). It seems relatively straightforward to introduce the flag now or later (I don't have a super strong opinion about what is best). @curino, it sounds like you have an initial usecase where best effort would be immediately valuable? In your use case do you always apply a post-filter, then?

**Comment by curino** [comment]
There are cases where the best effort is valuable,  e.g., for a cache like system that can provide some degree of pushdown if it is sitting in front a store/format that supports less/no pushdown. In such a settings you would want to have a fixed plan that does the post filtering and whichever part is cached (possibly only known at runtime) will get the accelerated pushdown behavior. 

Now these are not fully hypothetical scenarios but also not something we will use substrait for within short term, so ok to leave best effort as a later addition if as you say it will be a natural extension.

<2cents/>

**Comment by westonpace** [comment]
There may be more we can express here but I am not actively working on this and will close until I come back to it at some point.  I think the clarification we have done is probably sufficient.
