### ISSUE TITLE
An extensible ReadRel::LocalFiles::FileFormat

### ISSUE THREAD

**Issue by westonpace** [substrait-io/substrait#138]
Right now, if a producer & consumer wanted to support some unsupported (potentially internal/proprietary) file format they would need to create an entirely new relation extension or bury it in the hints, both of which seems a little heavyweight.

Making FileFormat a string would be something of a compromise / hack for extensibility

A string will probably fall short in some cases (e.g. with compressed CSV you would want to know what kind of compression has been applied) though an enum would equally fall short.

**Comment by jacques-n** [comment]
There is a third option: using a ExtensionTable.

That being said, I agree that it would be nice to make file format extensible. What do you think about switching it to a union that has a the enum or a `google.protobuf.Any`?

**Comment by westonpace** [comment]
Coming back around to this I think that sounds fine for a short term solution.  Longer term I suppose we might want some kind of formal extension point.  For example, there may be many engines that read CSV and if they all had a consistent way to express what kind of delimiter to expect it would be nice.

**Comment by westonpace** [comment]
Closing as addressed by #169
