### ISSUE TITLE
Setup automated releases

### ISSUE THREAD

**Issue by jacques-n** [substrait-io/substrait#141]
@cpcloud and I have been discussing introducing automated releases/release notes and starting to version things. We should get this going since other projects would be much better off depending on a released set of substrait proto definitions, etc as opposed to using a git hash.

**Comment by cpcloud** [comment]
Yep, I can look into this.

**Comment by winningsix** [comment]
Any more details for this? One quick question around this, for a ```Substrait``` dependent project, will Substrait be linked as a Git submodule or include protobuf there?

**Comment by jacques-n** [comment]
I think this will depend on the language. For things like Javascript, Java and, python I think we should publish compiled files. For c and c++ I think we should probably publish a tgz with the proto files. What do others think?

**Comment by FelixYBW** [comment]
Do we have plan to create and release the helper tools for each language as well? Like substrait_plan_builder etc.? The builder function will be useful to create and test substriat plans consumers. If so for c/c++ we may need to publish a library as well in future.

**Comment by jacques-n** [comment]
> Do we have plan to create and release the helper tools for each language as well? Like substrait_plan_builder etc.?

Yes, I think we should do that. I'm definitely trying to provide that as part of the [java patch](https://github.com/substrait-io/substrait/pull/120) I'm working on.
