### ISSUE TITLE
Does ReadRel::base_schema include columns hidden by projection?

### ISSUE THREAD

**Issue by westonpace** [substrait-io/substrait#158]
The `ReadRel` relation states:

Direct Schema | Defines the schema of the output of the read (before any emit remapping/hiding).
Projection | A masked complex expression describing the portions of the content that should be read

Does the `Direct Schema` include fields hidden by `Projection` (which is not technically the same thing as emit remapping / hiding)?

**Comment by jacques-n** [comment]
The intention was before projection as well. Want to post a pr?
