### ISSUE TITLE
Tables are truncated and UI doesn't make it obvious the content is available

### ISSUE THREAD

**Issue by pitrou** [substrait-io/substrait#172]
With Firefox 99.0.1 the table at https://substrait.io/types/simple_logical_types/ is not readable with a reasonable font size:
![substrait1](https://user-images.githubusercontent.com/1721820/164182977-7fcc94fd-67b2-465c-9481-03523fa5e37c.png)

Even with a very small and uncomfortable font size, there is still some truncation happening:
![substrait2](https://user-images.githubusercontent.com/1721820/164183041-772523d9-c56c-4170-a176-e17e57c12178.png)

**Comment by jacques-n** [comment]
In Chrome, there is a horizontal scrollbar. Is that not appearing on Firefox? (I agree it isn't exactly pretty but want to clarify if it is cosmetic/usability or functional).

Thanks!

**Comment by pitrou** [comment]
Wow, I had missed the horizontal scrollbar at the bottom of the table. Yes, it does appear.
