### ISSUE TITLE
Add bool flag nullOnFailure in Cast Expression

### ISSUE THREAD

**Issue by ZJie1** [substrait-io/substrait#185]
In velox, there have a bool flag nullOnFailure   which  prevents throws and instead returns null on cast failure
Is there any plan that we add such flag in substrait?

**Comment by mbasmanova** [comment]
CC: @mbasmanova

**Comment by jacques-n** [comment]
This sounds like a good enhancement. You want to propose an update to the spec and proto representation? I might suggest using an enumeration instead of boolean just in case we need to introduce more variations later.

**Comment by ZJie1** [comment]
> This sounds like a good enhancement. You want to propose an update to the spec and proto representation? I might suggest using an enumeration instead of boolean just in case we need to introduce more variations later.

Sure, will send a PR.

**Comment by ZJie1** [comment]
@jacques-n @mbasmanova Please help review https://github.com/substrait-io/substrait/pull/186

**Comment by cpcloud** [comment]
Closed by #186.
