### ISSUE TITLE
Implement any missing rels specified in the substrait spec in protobuf (hash and merge join among those)

### ISSUE THREAD

**Issue by marin-ma** [substrait-io/substrait#189]
If we already have a physical plan that contains join operators, and we convert that plan into substrait and let it consumed by an execution engine. The substrait plan won't tell whether the join operator is a hash join or merge join. In this case, how does the execution engine know which physical plan to execute?

**Comment by cpcloud** [comment]
Currently this is up to the execution engine to decide. Right now, only logical plans are implemented. @jacques-n would know more, but I believe there are plans to add physical operators like hash join to the proto implementation (they exist in the spec https://substrait.io/relations/physical_relations/).

**Comment by jacques-n** [comment]
This is so weird, I was sure I responded to this message.

Yes, the spec already defines the different variations of joins in addition to the base logical join. No one has spent the time translating the spec into protobuf. @marin-ma, if you wanted to take up this task, that would be great!

**Comment by westonpace** [comment]
hash & merge join have since been added.  I took a pass through the document and created individual issues for the other relations.  I'm going to close this.
