### ISSUE TITLE
Commit syntax documentation

### ISSUE THREAD

**Issue by jvanstraten** [substrait-io/substrait#192]
The commit message syntax that is now required is currently not at all obvious to newcomers (or to me, tbh). @cpcloud, could you (or someone else who's used to the syntax) write an explanation in a CONTRIBUTING.md file and/or the website? Or is the intention to squash all incoming PRs and leave it up to maintainers to write properly formatted squash commit message? In that case the CI for checking the syntax shouldn't trigger on PRs, though.

See also https://github.com/substrait-io/substrait/issues/182#issuecomment-1122720956

**Comment by jvanstraten** [comment]
That page is already super helpful, yeah. In addition to that, maybe we should also define a list of scopes to use for this repo?

**Comment by cpcloud** [comment]
I've never used semantic release with a fixed set of scopes, though I know there are projects that do it.

It might be a bit of whack-a-mole, however, I'd be up for trying it out.

Do you have a list in mind?
