### ISSUE TITLE
Should we do something about protobuf IDLs not reachable from a Plan object?

### ISSUE THREAD

**Issue by jvanstraten** [substrait-io/substrait#193]
I've been wondering for a while now what the purpose is of [function.proto](https://github.com/substrait-io/substrait/blob/main/proto/substrait/function.proto), [parameterized_types.proto](https://github.com/substrait-io/substrait/blob/main/proto/substrait/parameterized_types.proto), and [type_expressions.proto](https://github.com/substrait-io/substrait/blob/main/proto/substrait/type_expressions.proto). The messages in them are not reachable from `substrait.Plan`, and it seems like they're mostly concerned with things that are communicated via YAML rather than via the plans. Are these files simply dead code that no one has yet removed, or do they still serve a purpose?

Note that capabilities.proto also isn't reachable, but I believe it is at least referred to from the website in relation to a gRPC-based handshake.

**Comment by jacques-n** [comment]
The purpose of these is to be able to communicate function definitions on the wire. For example, if an IDE probes a substrait consumer and asks "What are all the function signatures you support." I definitely was relying on these at one point in the substrait-java project (but don't remember offhand if that is still the case). 

One of the things that makes capabilities and the function definitions disconnected is that we don't have a "substrait protocol" if you will. Some way via rest or other rpc method a consumer and producer could interact. The handshake, function listings, capabilities, etc all fall into these categories. 

I'm inclined to leave as is for a little longer and see if we can better clarify the protocol side of things. Thoughts?

**Comment by jvanstraten** [comment]
Isn't that the purpose of the YAML files, though? `substrait.Capabilities.SimpleExtension` currently also refers to YAML URIs and function names, rather than listing all the function prototypes outright. The way I've been picturing the handshake-y protocol, based on what already exists, is:

 1) producer asks consumer for `substrait.Capabilities`;
 2) if needed (probably not, because in all likelihood it already needs to know what's in it in order to meaningfully use it, though I suppose a producer that merely parses some text format like SQL and doesn't do any form of optimization, like Isthmus, might not need to know what the functions do), the producer can download and parse (and cache) the YAML files for details;
 3) producer sends consumer a `substrait.Plan`;
 4) consumer sends producer the result data in [TBD] format.

Or the responsibility for compatibility could be shifted to the consumer:

 1) producer sends consumer a `substrait.Plan`;
 2) if needed (again, probably not, because the consumer would probably just reject plans that use any extension URI for which it doesn't already have the functionality hardcoded into it), the consumer can download and parse the YAML files for details;
 3) consumer sends producer the result data in [TBD] format.

That makes these protobuf messages seem like redundant, dead code to me, hence this issue.

This is me taking the existing messages and specification for gospel, though. IMO it'd be way better if simple extensions were always represented using binary protobuf for as far as plans are concerned, i.e. make the URIs refer to downloadable protobuf serializations, or otherwise make it abundantly clear that simple extension URIs should *never* be treated as anything more than just unique strings, which no software should *ever* have to deal with resolving or parsing, other than optionally requesting what the other end of a producer-consumer connection thinks it means. The YAML format could then just be something that a single, Substrait-maintained command line tool converts to protobuf form when a human creates or changes a simple extension, or vice versa for debugging. I've been banging my head against a wall trying to design proper semantic validation for YAML files for weeks now, so if that work only has to be done once and in a single programming language, that'd be great. It'd also save a good number of LOC and dependencies in the validator PR as it stands, and I haven't even done the actual validation yet...

**Comment by cpcloud** [comment]
Generating `.proto`s from the YAML seems ideal to avoid synchronization issues. Right now, it isn't clear whether the YAML or the corresponding proto is ground truth (I think it's the YAML, but only because that's what we reference whenever we're talking about it).

**Comment by jacques-n** [comment]
JSON schema is duplicative of the main body of the functions but it can't express a bunch of the type expression and parameterized_types objects. 

I also think it is important to say that there is a difference between humans writing things and machines exchanging things. The YAMLs purpose/design was to minimize the complexity of implementing new functions. I think it continues to serve that purpose well. It doesn't preclude the utility of having a binary representation of that same data for machine collaboration. On the flipside, protobuf is nigh impossible for users to create by hand.

I think the lack of other people working with several of these concepts yet may make them feel less useful. I suggest keeping them around until everyone is working with type expressions and parameterized types and then restart the discussion. As proof of that disconnect, I haven't heard about anyone yet trying to use the [antlr parser](https://github.com/substrait-io/substrait-java/blob/main/core/src/main/antlr/SubstraitType.g4) created to help work type expressions in the yaml file (afaict).

**Comment by cpcloud** [comment]
Do you have some examples of usage of the concepts that may help guide the rest of us?

**Comment by jacques-n** [comment]
> Do you have some examples of usage of the concepts that may help guide the rest of us?

A couple that come to mind:
- A top one would be validation that plans correctly describe the output type based on a given set of argument types. As I understand it, the validator doesn't yet implement this functionality.
- While a FE can be hand coded to produce a given output type, this is only in the case that a FE knows all function definitions at creation time. When a FE that wants to be able to consume a function definition at runtime and produce a correctly specified use of those functions (say a backend telling a frontend about a new udf that has been registered), it must be able to consume the type expressions and type parameters defined for that udf. Options it could have include:
    - FE loads yaml from internet
    - FE asks BE for that definition in yaml format.
    - FE asks BE for that definition in binary format. (the protobufs here)

**Comment by jvanstraten** [comment]
> As proof of that disconnect, I haven't heard about anyone yet trying to use the [antlr parser](https://github.com/substrait-io/substrait-java/blob/main/core/src/main/antlr/SubstraitType.g4) created to help work type expressions in the yaml file (afaict).

I have attempted it, but after about half a day of confusion about getting ANTLR to do much of anything I gave up. There is no interoperability between ANTLR and Rust, anyway. That's not to say it's not useful; I can read the grammar just fine, it's just (unfortunately) not useful for the validator directly. Also, I think I've mentioned before that it's ambiguous about precedence, i.e. I'm pretty sure a naive parser built using that grammar would say either do 2 + 3 * 4 = (2 + 3) * 4 = 20 (if left-associativity is default), 2 * 3 + 4 = 2 * (3 + 4) = 14 (if right-associativity is default), or yell about reduce-reduce conflicts and not do anything (the behavior I'm used to from bison). I was mostly just trying to get ANTLR to work because I was curious which of those it would do, to better understand the corner cases of the grammar.

I've since been messing around with an EBNF form that I am/was half planning to propose along with a rewrite of the associated spec page (it's still very ambiguous IMO, and trying to follow the current spec to the letter and supporting insane things that the spec doesn't explicitly disallow has proven unreasonable). It's so drafty that I hadn't even pushed it yet, but [here](https://github.com/jvanstraten/substrait/blob/84dec45e83ae78bbe9ccc194291b48554b7e9cae/text/type-expressions.ebnf) it is if you're interested (drafty in the sense that I'm still thinking about how to approach some things; the file itself should be perfectly readable and self-consistent, but includes some pretty big changes that would need to be discussed properly first). That said, EBNF is more like a de facto pseudocode syntax than something anyone can build a parser from, so arguably that's worse than ANTLR and I just need to get my act together and learn how ANTLR works, and then use that syntax (or a subset thereof so I can more easily generate a parser from it in Rust, idk).

Anyway, I'm perfectly content closing this issue. I don't think the files are in anyone's way, and the answer to my original question is clearly that they serve a purpose and thus aren't strictly speaking dead code, even if no one is likely to be using them yet.

**Comment by jacques-n** [comment]
> I have attempted it, but after about half a day of confusion about getting ANTLR to do much of anything I gave up. There is no interoperability between ANTLR and Rust, anyway. 

Dumb question, other than requiring a nightly build of rust (which seems like it would probably be fine for the validator but not Substrait client libraries), is there something else that makes [antlr-rust](https://crates.io/crates/antlr-rust) unusable?

**Comment by jvanstraten** [comment]
Ah, right, I do recall stumbling on that when I looked for ANTLR bindings, too. I disregarded it because:

 - this is just some guy implementing these bindings on their own, without any form of support or maintenance from the ANTLR project itself
 - it's not very active (the last commit being in January)
 - potentially incomplete based on the readme, but I didn't try it for myself
 - AFAICT it requires a fork of ANTLR to build the bindings
 - it requires using an unstable/nightly build of the Rust compiler (i.e. use of unstable Rust language features, which is viral in the sense that any dependent projects are then forced to use it as well)
