### ISSUE TITLE
Confusion about interval types (and type compliance in general)

### ISSUE THREAD

**Issue by jvanstraten** [substrait-io/substrait#195]
The way the documentation describes `interval_year` and `interval_day` has always confused me. What I intuitively feel like it *should* say is that `interval_year` describes a timestamp difference with month granularity (with the purpose of being able to say "next month" or "next year" despite the actual timestamp difference implied with that being context-sensitive), `interval_day` describes an exact timestamp difference with at least microsecond granularity, and both types must support a range of at least +/-10000 years. If I were to start from scratch with a data storage format for these types, I would probably use a single i16 signifying months for `interval_year`, and distribute `interval_day` over i64 seconds and i32 microseconds (or nanoseconds) because that's the distribution I'm used to from Linux and C.

Following [the relevant part of the spec](https://github.com/substrait-io/substrait/blob/720dbeac31f11655514cd737815d0bac0ad47fc8/site/docs/types/simple_logical_types.md?plain=1#L22-L23) to the letter however, my takeaways are:

 - `interval_year` *must* be stored as two separate integers, one for years and one for months, because for example 1y0m is defined to be different from 0y12m. Otherwise, I don't understand what all the examples are for; a range [-12000, 12000] months would have sufficed, and the rest would just be describing the semantics of a string to `interval_year` conversion.
 - Likewise, `interval_day` *must* be stored as two separate integers, one for days and one for at least microseconds; I couldn't, for example, reuse `DECIMAL<18, 6>` (signifying seconds) or (equivalently) i128 microseconds, or use seconds/microseconds as I probably would have done otherwise.
 - The microsecond portion of `interval_day` must be stored as at least an i64, either with microsecond or nanosecond granularity (it took me a while to figure out that those numbers are based on 2^63/1000).
 - Unlike `interval_year`, `interval_day` can legally assume values beyond +/-10000 years, for example by setting both day and micros to the maximum or minimum value.

Notably, the Arrow data type marked as equivalent for `interval_year` wouldn't be compliant; Arrow stores `INTERVAL<YEAR_MONTH>` as a single i32 specifying months. `INTERVAL<MONTH_DAY_NANO>` (i32 months, i32 days, i64 nanos) is also not an exact match with `interval_day`, but AFAICT it's at least a superset thereof.

I would propose to rewrite/clarify the specification of the data types after we answer the following questions:

 1) Would it be sensible to rewrite the docs for `interval_year` and `interval_day` based on the first paragraph, or is my lack of a background in data science showing?
    - If yes, should we change the names to `interval_month` and `interval_micros`, or something else that better captures what they represent?
 2) Should types in general be specified by means of some canonical in-memory format, or merely represent abstract sets of possible values that are hopefully convenient?
    - Integers and arguably floating points are currently specified as the former, intervals strongly imply a particular physical representation, and most of the other types are specified abstractly.
    - AFAICT [the answer to this one the latter](https://github.com/substrait-io/substrait/blob/720dbeac31f11655514cd737815d0bac0ad47fc8/site/docs/types/type_variations.md?plain=1#L3), i.e. type variations should be used to specify the physical storage type when needed, so the base types can be defined abstractly.
 3) Should it be legal for implementations to internally operate on values outside the Substrait-specified range, if they use a different physical representation internally?
    - If yes, this would allow Arrow to use `INTERVAL<MONTH_DAY_NANO>` without additional checks, but it might allow for a lot of subtle undefined behavior in practice. For example, 1 microsecond divided by 3 could then be rounded to 0 microseconds by one engine, and to 333 nanoseconds by another. Not sure what the best approach would be here, or if these corner cases are even something we need to care deeply about.

**Comment by jacques-n** [comment]
I think there are several things here. 

## Table stuff
For, the table where we compare to existing system types: this wasn't meant to imply exactly equivalence. I'm generally inclined to remove other systems columns of that table all together. It creates a caste mentality which I'd prefer not to have and it seems like it only serves to confuse on the exceptional cases.

## Answers to your questions
1. In general, it seems weird to define intervals as a difference. They are a clear independent concept. I'm happy for you to enhance what is said but I'd expect most people who engage with Substrait to already have a really solid understanding of what intervals are. Amongst other things, they are defined in the ANSI SQL specification.
    1. No, I don't think this makes sense. The names were chosen to try to closely correspond to what they are called in the SQL specification (and what is used in most databases). They describe the scope of impact, not the scale. The full names would be `INTERVAL YEAR(A) TO MONTH(B)` and `INTERVAL DAY(X) TO SECOND(Y)` where A,B,X,Y are the resolution of the range. Yes, the choice here was to use `INTERVAL_YEAR` as opposed to `INTERVAL_YEAR_MONTH` just to make things shorter. That may have caused some of the confusion.
2. The definition goal in the spec was abstract sets.
    1. This feels like a non-problem. Integers use names that are helpful to people, however I believe that we still define them as abstract sets [-128 to 127]. Yes, we say 8bits for i8 because that's likely to be the representation. But it isn't required. It's just helpful for spec readers.
3. This feels like a case where Substrait would say that this is just undefined behavior. If you wanted to define behavior or this, you'd be best to define a new data type. I'd expect the validator to reject literals outside of the allowed range.

## Arrow collapse of types
WRT to Arrow and months instead of years + months. I don't see this as a problem. This is more the domain of making sure we have clear definitions of the function behaviors when working with Interval. Most databases specify that logical conversions are considered equivalent values with interval types. If you add 8 months and 8 months, you can legally get 1y4m or 16m. If you add 1y2m and 2m, a perfectly reasonable return value is 16m (or 1y4m). Basically, a system is free to represent those interchangeably and move from one to the other at will. This is consistent with how most databases work (including Arrow, I believe). We could consider going to so far as defining that these are interchangeable in Substrait. I didn't because our goal is generally to avoid being lossy.

**Comment by jvanstraten** [comment]
> In general, it seems weird to define intervals as a difference. They are a clear independent concept.

If they're not a time difference, I'm honestly pretty stumped about what they are... When I first saw the definition, my response was "did they seriously use the same data structure, i.e. a two-tuple, for an interval as in something on the number line like 5..10 and an interval as in the length of a span of time, just because the English word for both of those is the same and someone once ran into a grammar conflict?" Because that's suspiciously what it looks like to me. Anyway, it doesn't really matter whether I understand the reasoning behind the type if everyone else does.

The rest of what you said about intervals makes sense to me. To summarize it in my own words (correct me if I'm still misinterpreting): 1y0m normally *is* functionally indistinguishable from 0y12m, so as far as Substrait should be concerned they are just different physical representations of the same logical value. That makes it an implementation detail whether it's actually implemented as a single integer with a range of at least +/-12000 or as the two separate integers. Thus, the spec can be reworded to something like "an interval representing a number of months in the range [-12000..12000], usually represented as some number of years and some number of months" (so it's also clear to people who aren't used to database jargon, like me) and Arrow's representation matches that.

> WRT to Arrow and months instead of years + months. I don't see this as a problem. This is more the domain of making sure we have clear definitions of the function behaviors when working with Interval.

What concerns me from an Arrow perspective is that people can also define new extension functions based on these types, that don't have this implied-to-be-sane behavior. User-defined functions especially will be out of anyone's control once added. For example, someone would presumably be able to write UDFs that pack and unpack the components of an `interval_year` into two integers. If Arrow would use its physical representation, they could write unpack(pack(3, 14)) and then rightfully complain when Arrow hands them (4, 2) instead. If the spec were explicit at the type level about 3y14m and 4y2m being the same thing, i.e. 50 months, the user would be wrong to expect (3, 14) exactly. That's why I want the spec to be clear about what these *types* mean, not just the operations on the types. It'd be a breaking change to extend the minimum set of functionally distinct values that a type can assume, but adding a function with new behavior wouldn't be.

Likewise, in general I think the spec should be more explicit about what is an example (like i8 being implemented as a byte; i.e. it could also be a signed 3-digit BCD, 9-bit sign-magnitude, or a 32-bit integer, as long as this is transparent to the behavior of a plan that only operates on i8s that are actually within [-128..127]) and what is an actual requirement for compliance. Otherwise people could treat the whole Substrait spec as an example of what to put in the proto messages, which from what I've seen isn't as much of a hyperbole as I'd like it to be. So that's one of the things I want to gradually start working on, now that the validator is under review.

Some context maybe, as for what I'm even doing here if I don't have a database background, and where I'm coming from with all this: my background is in compilers, interface generation, and low-level optimization stuff, mostly FPGA-based. I'm used to finding and needing to be pedantic about the most ridiculous corner cases, simply because people expect compilers to always be right, people will angrily point fingers at each other if the interface was open to interpretation, low-level code will just throw a segfault at you if you do it wrong (if you're lucky), and if you get something wrong in an FPGA accelerator card... well, a trip to the data center to power cycle the machine and hope it boots back up it is. One does not simply submit a patch after the fact to fix those types of problems. But maybe I just need to learn to chill a little in this context...?

> I'd expect the validator to reject literals outside of the allowed range.

It does, don't worry :) The way I see it, literals are logical values, so they have to be within the logical range.

Other than those points I agree with what you've said. I'll probably submit a PR based on this next week.
