### ISSUE TITLE
Add a github workflow step that verifies correctness of the .proto files before merge

### ISSUE THREAD

**Issue by jacques-n** [substrait-io/substrait#20]
Right now, there is no pre-commit step that verifies the proto files are valid. We should add something that verifies this (even though we don't release any artifacts based on the proto files).

**Comment by cpcloud** [comment]
looks like this could be of interest at some point if perhaps overkill at the current moment https://buf.build/blog/github-actions-for-buf-now-available

**Comment by cpcloud** [comment]
backwards compatibility verification being of future utility
