### ISSUE TITLE
Clarfiying JOIN_TYPE_SINGLE

### ISSUE THREAD

**Issue by westonpace** [substrait-io/substrait#206]
Is `JOIN_TYPE_SINGLE` a left inner join or a left semi join?  Also, couldn't any join potentially have multiple join matches per key?  Instead of a standalone join type would it make more sense to add a separate property to `JoinRel`?

```
enum MultipleKeyBehavior {
  // Producer doesn't care
  UNSPECIFIED = 0;
  // Return an error if there are multiple matches for a key
  ERROR = 1;
  // Return only a single match (not really the "first" as there is no ordering)
  SINGLE = 2;
  // Return a row for each combination of keys
  CROSS = 3;
}
```

**Comment by westonpace** [comment]
CC @pdet

**Comment by save-buffer** [comment]
Regarding this `SINGLE` join, this seems like it is a special case of a `GroupJoin` operator with `any` aggregate. I think `SINGLE` should be removed entirely in favor of either: 
- requiring a GroupBy before/after the join to achieve this behavior (and letting implementations fuse `GroupBy` with `Join` during substrait parsing into `GroupJoin` if it's supported)
- adding a native `GroupJoin` to substrait (and letting substrait consumers decompose it into `GroupBy` and `Join` during parsing if there is no native `GroupJoin`).

Not clear which is better, it is very much a RISC-vs-CISC debate.

**Comment by cpcloud** [comment]
It is neither a left inner join (which isn't a kind of join, I assume you mean inner join) nor a left semi join.

Single join is a special kind of join used to capture the semantics of certain kinds of correlated subqueries as (better-than-nested-loop) join instead of a correlated subquery or NL join.

It's similar to an outer join, with the restriction that only a single tuple can be produced when the predicate is true.

[This paper](https://15721.courses.cs.cmu.edu/spring2018/papers/16-optimizer2/hyperjoins-btw2017.pdf) describes the single and mark joins along with examples.

`GroupJoin` with `any` isn't a replacement since it doesn't capture the error semantics of a single join.

**Comment by curino** [comment]
Is it ok if we start inlining comments about things like this? 

E.g., : 
```
  enum JoinType {
    JOIN_TYPE_UNSPECIFIED = 0;
    JOIN_TYPE_INNER = 1;
    JOIN_TYPE_OUTER = 2;
    JOIN_TYPE_LEFT = 3;
    JOIN_TYPE_RIGHT = 4;
    JOIN_TYPE_SEMI = 5;
    JOIN_TYPE_ANTI = 6;
    // This join is useful for nested sub-queries where we need exactly one tuple in output (or throw exception)
    // See Section 3.2 of https://15721.courses.cs.cmu.edu/spring2018/papers/16-optimizer2/hyperjoins-btw2017.pdf
    JOIN_TYPE_SINGLE = 7;
  }
```

I think it would save people time, as I had to search around here to understand what `JOIN_TYPE_SINGLE` was used for. If we agree to start populating the .proto with lots of self-contained comments I can start doing it as I don't understand something and have to dig around about it. This should also show up in `buf` docs, and if we start linking in the spec the .proto also there, which would make semantics/coverage understanding more accessible I think.

**Comment by jacques-n** [comment]
I'm supportive of inlining as long as we make sure to embed the appropriate proto in the docs as well.

**Comment by jacques-n** [comment]
@westonpace thoughts on next steps here?

**Comment by westonpace** [comment]
I've run into this question once or twice since creating this issue.  I've found that the markdown describes the behavior quite well.  So I don't think there is an urgent need for any change and I'll close this.
