### ISSUE TITLE
Figure out new sync meeting host

### ISSUE THREAD

**Issue by westonpace** [substrait-io/substrait#211]
The sync meeting currently uses google meet.  For personal accounts it appears that meetings are limited to 60 minutes in length.  Rather than have discussion get artificially cut off it would be nice to have a meeting host that allowed things to run a little late.

**Comment by jacques-n** [comment]
Happy to use our Google or zoom account for this.

**Comment by westonpace** [comment]
Thanks @jacques-n 

If we use Google Meet then I think the meeting will be associated with the owner of the event.  So you would need to recreate the event on the shared calendar.

Right now the Substrait shared calendar is shared with jac...dr...@gmail.com (mangled slightly to discourage crawlers).  If you want me to add a different email I can.  You would then need to create the new recurring meeting and I can delete the old one.

If we go with Zoom I think you can create a recurring meeting that isn't associated with any particular calendar and then I can just update the description of the event we already have.

I'm happy with either approach.

**Comment by curino** [comment]
I can also easily creating a Teams event (in fact we have one already in place with our folks, within which we have the google meets link ;-)).

**Comment by westonpace** [comment]
Let's make some progress on this before the next sync meeting (Jun 22).  I don't care too much between Teams, Zoom, or Meet but I think someone else is going to have to take the next step (create a meeting and share the link with me so I can put it into the calendar).

**Comment by ashvina** [comment]
I like @curino suggestion of using Teams, I find recordings and transcriptions capability really useful. I volunteer to create an invite. Please let me know if anyone has any suggestions or objections. Meanwhile I will try to find the official recommendations and if there are any known constraints.

**Comment by westonpace** [comment]
Closing as we now are using Teams.
