### ISSUE TITLE
Mismatch between site & protobuf in description of aggregate grouping sets

### ISSUE THREAD

**Issue by westonpace** [substrait-io/substrait#214]
The site description of an aggregate relation contains:

```
| Direct Output Order  | The list of distinct columns from each grouping set (ordered by their first appearance) followed by the list of measures in declaration order, **followed by an integer describing the associated particular grouping set the value is derived from.** |
```

```
| Grouping Sets    | One or more grouping sets.                                   | Optional, required if no measures.      |
| Per Grouping Set | A list of expression grouping that the aggregation measured should be calculated for. | Optional, defaults to 0.                |
```

There does not appear to be any representation of `Per Grouping Set` in the protobuf.

Also, some questions:

 1. Does the extra integer column describing the grouping set get included in the output even if there are measures?
 2. What in the world is a grouping set?

**Comment by jacques-n** [comment]
The protobuf exposes grouping sets as a list of groupings (where each grouping is a list of discrete expressions). Grouping sets come from the sql feature of the same name.

**Comment by jacques-n** [comment]
The intention was to include the grouping ID in all outputs unless one remaps (whether there are measures or). 

That being said, we should consider whether we state that the column exists only in the case of two or more grouping sets. It's pretty pointless in the case of zero or one grouping set.

**Comment by westonpace** [comment]
Hmm...can we rephrase `The list of distinct columns from each grouping set (ordered by their first appearance)` to something like `The output value from each grouping expression`?

The fact that values are `distinct` seems to be unrelated to the output order.

What is a `grouping ID`?  For example, if I have:

```
SELECT MEAN(cost) FROM products GROUP BY category, vendor
```

And my input data is a single row

cost | category | vendor
--- | --- | ---
20 | toys | target

and my output data is then (I think)

category | vendor | MEAN(cost) | grouping set id
--- | --- | --- | ---
toys | target | 20 | ???

**Comment by jacques-n** [comment]
The "distinct columns..." could be "distinct expressions..." but it does directly influence things. Imagine a query like:

```
SELECT state, city sum(sales) as sales from t GROUP by GROUPING SETS ((state,city), (state))
```

The current definition of the grouping would give an output something like:

|State|City|Sales|Grouping Set Id|
|-|-|-|-|
|California|San Francisco|10|0|
|California|San Jose|1|0|
|California|Calistoga|5|0|
|California| |16|1|

The key is we don't want to output the same expressions that is defined in separate grouping sets multiple times. 

So if we remove grouping sets and just have something like
```
SELECT state, city sum(sales) as sales from t GROUP by state
```

I'd expect to still get a grouping id (but only one).
|State|Sales|Grouping Set Id|
|-|-|-|
|California|16|0|

**Comment by westonpace** [comment]
Ok.  I've got some more reading to do but this makes sense.  I'll reopen if I end up with more questions later.
