### ISSUE TITLE
Establish intended scope of functions in `extensions/*.yaml`

### ISSUE THREAD

**Issue by ianmcook** [substrait-io/substrait#307]
Some folks at Voltron Data have been working to add more functions in the [extensions YAML](https://github.com/substrait-io/substrait/tree/main/extensions). Along the way, we have gained a clearer understanding of when a function should be considered in scope versus out of scope for Substrait. Here are some guidelines that have emerged:

- Avoid adding a new function if is is merely syntactic sugar and if producers could express its behavior easily enough by composing other existing functions. However, it might be acceptable to add such a function if adding it can enable consumers to more efficiently execute plans, or if adding it can avoid producers deconstructing a syntactic construct that consumers then need to reconstruct.
  - Example: https://github.com/substrait-io/substrait/pull/287#discussion_r942705485
- Avoid adding functions that express behaviors that are already expressible with [specialized record expressions].(https://substrait.io/expressions/specialized_record_expressions/)
  - Example: the `if_else` function originally proposed in #291
- Prefer adding new options to existing functions instead of adding new functions.
  - Example: #289
  - Example: #295
- Aim for syntactic and semantic consistency with widely used SQL dialects, especially PostgreSQL.
  - Example: https://github.com/substrait-io/substrait/pull/285#discussion_r944542030

Are there any other important guidelines I'm missing here?

Should we document this somewhere?

**Comment by ianmcook** [comment]
To share some further context about how the folks at Voltron Data chose which functions to add:

We went through the functions documentation for various SQL engines and other data processing libraries (PostgreSQL, DuckDB, MySQL, Hive, Impala, Acero, NumPy/pandas, R/dplyr, and more) and made a big list of the functions that exist in many of these systems. We then applied some subjective judgements based on our experience to make a few additions and removals, and set the names to (mostly) consistent with what things are named in PostgreSQL.

Here is the list that come out of that. Note that the categories in this list are more fine-grained than the categories used to organize these functions into YAML files. A checked box indicates that the function was deemed to be in scope. An unchecked box indicates that the function was deemed to be out of scope for the stated reason.

## Arithmetic functions
- [x] `abs`
- [x] `add`
- [x] `divide`
- [x] `factorial`
- [x] `modulus`
- [x] `multiply`
- [x] `negate`
- [x] `power`
- [x] `sign`
- [x] `sqrt`
- [x] `subtract`

## Rounding functions
- [x] `ceil`
- [x] `floor`
- [x] `round`
- [ ] `round_to_multiple` - expressible by composing other functions
- [x] `trunc`

## Logarithmic and exponential functions
- [x] `exp`
- [x] `ln`
- [x] `log10`
- [x] `log1p`
- [x] `log2`
- [x] `logb`

## Trigonometric functions
- [x] `acos`
- [x] `asin`
- [x] `atan`
- [x] `atan2`
- [x] `cos`
- [x] `cosh`
- [x] `sin`
- [x] `sinh`
- [x] `tan`
- [x] `tanh`

## Comparison functions
- [x] `between`
- [x] `equal`
- [x] `greatest`
- [x] `gt`
- [x] `gte`
- [x] `is_finite`
- [x] `is_infinite`
- [x] `is_not_distinct_from`
- [x] `least`
- [x] `lt`
- [x] `lte`
- [x] `not_equal`

## Logical functions
- [x] `and`
- [x] `and_not`
- [x] `not`
- [x] `or`
- [x] `xor`

## Conditional functions
- [ ] `case_when` - expressible with specialized record expressions
- [ ] `choose` - expressible with specialized record expressions
- [x] `coalesce`
- [x] `is_nan`
- [x] `is_not_null`
- [x] `is_null`
- [x] `nullif`

## Conversion functions
- [ ] `cast` - expressible with specialized record expressions

## String trimming functions
- [x] `ltrim`
- [x] `rtrim`
- [x] `trim`

## String containment functions
- [x] `contains`
- [x] `count_substring`
- [x] `ends_with`
- [x] `like`
- [x] `regexp_count_substring`
- [x] `regexp_match_substring`
- [x] `regexp_strpos`
- [x] `starts_with`
- [x] `strpos`

## String transform functions
- [x] `bit_length`
- [x] `capitalize`
- [x] `char_length`
- [x] `concat`
- [x] `concat_ws`
- [x] `left`
- [x] `lower`
- [x] `octet_length`
- [x] `title`
- [x] `upper`
- [x] `regexp_replace`
- [x] `repeat`
- [x] `replace`
- [x] `replace_slice`
- [x] `reverse`
- [x] `right`
- [x] `substring`
- [x] `swapcase`

## String padding functions
- [x] `center`
- [x] `lpad`
- [x] `rpad`

## Set containment functions
- [x] `index_in`
- [ ] `is_in` - expressible with specialized record expressions

## Random number generation functions
- [x] `random`

## Datetime functions
- [x] `add_intervals`
- [x] `assume_timezone`
- [x] `extract`
- [x] `strptime`
- [x] `strftime`

## Aggregate functions
- [x] `any_value`
- [x] `approx_count_distinct`
- [x] `approx_median`
- [x] `approx_quantile`
- [x] `avg`
- [x] `bool_and`
- [x] `bool_or`
- [x] `corr`
- [x] `count`
- [x] `count_distinct`
- [x] `max`
- [x] `min`
- [x] `sum`
- [x] `median`
- [x] `mode`
- [x] `product`
- [x] `quantile`
- [x] `std_dev`
- [ ] `std_dev_pop` - implemented as an option to `std_dev`
- [ ] `std_dev_samp` - syntactic sugar
- [x] `string_agg`
- [x] `variance`
- [ ] `variance_pop` - implemented as an option to `variance`
- [ ] `variance_samp` - syntactic sugar

**Comment by ianmcook** [comment]
@jacques-n I heard (via @thisisnic) that you asked in the biweekly meeting for me to share this list ☝️ Let me know if this is helpful!

**Comment by jvanstraten** [comment]
> Should we document this somewhere?

Yes! I copied your items one-to-one into a new page on the website in #301, and also added a few of my own:

 - Generalize the function as much as possible, to reduce the odds that we'll need to update it later.
    - Example: for a function like `add`, consider making it variadic rather than only accepting two arguments.
 - Be consistent when it comes to argument types. It is preferable to define a function that accepts and returns one type class over a function that promotes from one type class or another or accepts a mixture of type classes. This aims to prevent an explosion of function implementations.
    - More information and examples: [#251](https://github.com/substrait-io/substrait/issues/251)
 - Be pedantic when describing functionality. The corner cases that rarely come up in practice are exactly the places where different implementations are likely to differ, so for a plan to be implementation-agnostic, these are exactly the things that need to be specified exhaustively. For especially pedantic things, an optional enumeration argument may be suitable; this allows a producer to explicitly indicate that the consumer can pick the behavior.
    - Example: the verbosity of the description of [regex_match_substring](https://github.com/substrait-io/substrait/blob/fbe5e0949b863334d02b5ad9ecac55ec8fc4debb/extensions/functions_string.yaml#L79-L139).
    - Example: the floating point rounding option defined [here](common_options.md).
 - The core extensions should generally not be defining type classes. If you believe a type class that isn't currently in the specification is important enough to include, it probably makes more sense to simply add it to the built-in types, or otherwise should be a third-party extension.

**Comment by westonpace** [comment]
@ianmcook Is this issue complete at this point?

**Comment by ianmcook** [comment]
> @ianmcook Is this issue complete at this point?

Yes. This was more of a discussion than an issue. I will close it.

**Comment by ianmcook** [comment]
Clarification: the list of functions in [the comment above](https://github.com/substrait-io/substrait/issues/307#issuecomment-1235841379) is non-exhaustive. Further digging is required to expand this list. I expect that further digging will turn up at least 20 more functions that clearly meet the criteria described above.
