### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by jvanstraten** [substrait-io/substrait#348]
As the project is stabilizing more and more, I think it would make sense to think a little more deeply about how the protos should be structured, come up with guidelines, and do a refactor to weed out the inconsistencies that will come out of that before we ultimately go to 1.0.0. Some categories of things that I'm talking about:

 - *Cleanliness and future-proofing.* The oneof vs enum discussion we just had in the sync meeting (see also https://github.com/substrait-io/substrait/pull/336#discussion_r981437779). If we merely make that change going forward, it forms an inconsistency. Some places in Substrait using booleans for nullability and others using an enum is another one I'd put in this category. Likewise for signed vs unsigned integers and the integer sizes in literals and type parameters where negative numbers make no sense, and in general I feel like we should be using `sint` (zigzag-encoded, takes 1 byte for `-1`) types rather than `int` (plain 64-bit variable length encoding where `-1` takes IIRC 10 bytes to encode) if we really care about serialization size. These things don't necessarily help anyone right now, but make the whole thing more consistent, while requiring only a few lines of code here and there, if anything (they are mostly just breaking changes for the serialization format).

 - *Usability improvements.* This category requires more code changes now, but I think could save A. LOT. of misery down the line, and I say that because I have been experiencing that misery writing the validator. I feel like a lot of the protos were developed pretty ad-hoc and/or as part of the original sketch just to get something out there that works for now, rather than something intended to be there forever, and in some cases I just don't think the message types or semantics make sense and end up requiring a whole lot of strange special-case-y spaghetti code to implement correctly, when just changing a few words in the spec could have avoided the whole problem completely. Some examples:

    - Asserting that extension names should match the commonly accepted regex for identifiers. If we *don't* assert that, everyone who ever wants to make a parser for any of this is going to have a heck of a time, and we can never unambiguously introduce a namespace separator of sorts in any backward compatible way either (what does the identifier `...` refer to when `.` is also used as a namespace separator? Answering this question took quite a bit of very cursed code in the validator, to prepare it for YAML dependencies). IMO this just doesn't weigh up to users being able to use `+` for their function name instead of `add`, when in all likelihood they need generic name conversion code for Substrait core anyway.
    - Literals have nullability and the type variation outside the oneof, while types have those things replicated across all type messages. Both styles suck -- I recognize that this is a protobuf expressiveness problem that's not easily solved -- but as a (sort of) consumer, that forces me to come up with a pattern for dealing with both of these things, rather than just having to deal with one of them. For this particular thing I've been doing thought experiments about adding a consistent layer on top of protobuf to deal with inheritance (after all, inheritance *can* be modeled using oneofs and composition) that a consumer or producer *could* then choose to convert automatically using code generation or template logic, but doesn't necessarily have to use because it's still just protobuf one layer down. I'd then also generalize advanced extensions across all messages, so we don't have to bicker about adding a new advanced extension field every time someone wants something we hadn't thought of yet (isn't supporting that the point of extensions in the first place?).

   I'll be happy to make a much more comprehensive list of these things if we want to tackle this sort of thing, but it would take me a while.

 - *Getting rid of deprecated fields that have accumulated.* The point of deprecation is to give users time to make a change rather than requiring them to make it immediately. That's fine. However, if a consumer wants to actually be compatible with producers that still use the deprecated fields, they need to at least duplicate a bit of consumption code. Likewise, if a producer wants to be compatible with consumers that can't be bothered with this and only read the new style, they also have to duplicate code. In the validator it's even worse because I have to not only support both but also check that both styles mean the same thing if they are both specified. This actually does add code and complexity, and unless eventually removed, is cumulative and sometimes exponential. On the other hand, due to the phase the project is in, the deprecated fields are unlikely to *actually* be used by anyone in practice, so this compatibility code is unlikely to be hit. A new user who isn't aware of this history will not know this though, and if they're like me, they'll end up wasting their time.

(I might add some more points as I come up with them)

For some of these things *on their own* I see the point I think Jacques was trying to make before we ran out of time, i.e. there is no value to changing this *other* than consistency while requiring everyone to make the change costs effort, and therefore it isn't worth the breaking change. This is part of why I think it's a good idea to refactor in one go. If and when something comes up that is so disruptive that everyone will need to put considerable effort into making the change anyway (IMO changing the way function arguments work is one of them -- not a single practical plan out there right now will survive that change), isn't it better to actually fix all the "meh" things that have accumulated as well?

Also, isn't this the reason why we made the project 0.x rather than starting with 1.x? I'm a big proponent of making backward compatible changes, but only if the original logic was also sensible and no breaking changes are required for anything else. That's how things should be for 1.x and above, when you already have a stable and time-tested core. That just isn't the case with Substrait yet, evidenced by the fact that we very regularly have to make breaking changes to beat a preexisting feature into submission to make it work in the context of something we just hadn't thought of. Especially for a specification project, avoiding breaking changes *once stable* should be one of the top priorities, and the way I see it, you can only accomplish that via consistency and generalization, because making sure the primitives are sound and letting people build from there is the only way to actually support things you haven't thought of yet. You just can't do that one use case at a time. So, I strongly believe we should make the effort to stabilize core features now that we can still do so without causing too much grief.

**Comment by jacques-n** [comment]
I'm generally unsupportive of refactoring unless it presents a substantial nearterm benefit. As a community where much of the work against Substrait happens outside the core repository, refactoring puts a major burden on others. I generally reject that now is a good time to refactor. The idea that "we know better" will always be true. Tomorrow we're realize that some of the choices we made (or refactored) today, could have been better.

I don't consider removal of deprecated fields to be refactoring. I propose we just have a time pattern for now on that. E.g. 3 months after we deprecate, we remove for now (or similar).

**Comment by westonpace** [comment]
I'm going to close this since the discussion seems to have gone stale.
