### ISSUE TITLE
Advanced extension refactoring

### ISSUE THREAD

**Issue by jvanstraten** [substrait-io/substrait#350]
Something to go along with #348. If we decide not to care about fixing things that are awkward but not necessarily *broken*, I guess this can just be closed, but in the interest of having discussions and thoughts out in the open I'll just throw this out there anyway.

IMO the concept of having advanced extensions and differentiating between ones that can be ignored if unrecognized and ones that can't be is great, but there are a number of inconsistencies and awkward things in the protos right now.

 - Redundancy. Many extension specifications are highly redundant. For example, `RelCommon` includes a `hint` field with a generic `AdvancedExtension` contained within (as well as a number of other fields), but also directly includes an `AdvancedExtension`. Not to mention that some relations have an advanced extension of their own.

   | | optimization | enhancement |
   |-|-|-|
   | ReadRel.advanced_extension | generic hint | generic semantic change |
   | ReadRel.common.advanced_extension | a *more* generic hint? | a *more* generic semantic change? |
   | ReadRel.common.hint.advanced_extension | also a generic hint? | ??? |
   | ReadRel.common.hint.stats.advanced_extension | stats go here I guess? | ??? |
   | ReadRel.common.hint.constraint.advanced_extension | ??? | ??? |

   What is a "constraint" if it can be ignored per the semantics of the "hint" field it's contained in, or the optimization field of `AdvancedExtension` itself? Likewise for any enhancement contained within hint?

   IMO we should *either* embrace the redundancy and add an `advanced_extension` field to *every* message (this actually is a very common thing for ASTs and IRs, except they're usually called annotations), *or* place the extensions more selectively (and probably replace a number of these with raw `Any`s or repeated `Any`s).
 - Naming inconsistency: optimization vs hint, enhancement vs semantic. I'd vote hint (because it's broader but shares the same implied semantics) and enhancement (because noun).
 - Currently, each extension field can only hold a single `Any` message for each type of extension. I see that as a problem especially for hints. What if a plan transformation wants to add hints to the plan, but a target hint field is already populated with an extension it doesn't know about? By Substrait's rules it should be allowed to ignore that extension because it has no semantic meaning, and should thus be able to add its own hints, but currently can't. Likewise, the `Plan.advanced_extensions` field can only hold one extension of each type (hint aka optimization & enhancement), despite the plural form of its name.
 - Lack of a specification for what the `Any` type URLs should look like. As far as I've been able to tell, libprotobuf doesn't actually do anything with `Any` messages unless you explicitly tell it to serialize/deserialize them. I ended up doing some tests with the Python bindings of libprotobuf. When you `Pack()`, it seems to set the `type_url` field to `type.googleapis.com/<namespaced-protobuf-type-name>`, for example `type.googleapis.com/substrait.Plan`. The `TypeName()` function returns only the protobuf type name. It seems that you can override the type URL to whatever you want; `TypeName()` just seems to return whatever's after the last `/`, and `Is()` seems to just blindly check whether `TypeName()` corresponds to the full name attached to a protobuf descriptor. Finally, regardless of whether `Is()` returns true for a particular descriptor, it'll let you `Unpack()` into whatever descriptor you give it, as long as the binary serialization is compatible. So it seems to me that Google made a mess of specifying how `type_url` is supposed to work, and in practice we can do whatever we want with them. All this is important primarily because of the `Plan.expected_type_urls` field, which I'm assuming should use the same strings as libprotobuf ends up using internally for `type_url`, though this is also not entirely clear (I just see a Java-specific type name referred to in its comment..)
 - What's the actual intended purpose of `Plan.expected_type_urls`? It says that the list may include things that aren't actually used, or things that are used but may be ignored by the consumer due to being hints. The validator happily checks that any `Any.type_url` in the plan is actually present in the list and gives you info messages if you have redundant ones, but other than that, I don't see what anyone can actually do with this field, or what would actually break if it's just left unspecified by a producer. It would make more sense if only the URLs of enhancements used in the plan would be in the list, so a consumer can quickly reject a plan if it encounters one it doesn't know about... but that still seems pretty redundant, because it should find out while parsing the tree naturally anyway.
 - IMO extension relations and extensions augmented by an enhancement should indicate what the output schema is. Otherwise, it's completely impossible to do type propagation in the presence of unknown extensions. This contrasts with simple extensions, where you can still do type propagation even without the extension descriptions (let along recognizing the extension) due to the redundant return type specification for function bindings.

**Comment by westonpace** [comment]
I'm going to close this as stale as no one is working on this at the moment.  As people begin to work more on features related to extensions (there has been some discussion, for example, about representing constraints) I think we can start to work through these.
