### ISSUE TITLE
Modulus function in functions_arithmetic.yaml is missing division-by-zero behavior

### ISSUE THREAD

**Issue by jvanstraten** [substrait-io/substrait#353]
IIRC there is no PR open for this at this time, so I guess we glossed over it during the consistency pass. It's also missing a specification of behavior for negative numbers.

**Comment by jordanvieler** [comment]
I have been looking into this issue, and it looks like modulo is defined differently by different languages. My impression is that would result in different results for zero and negative inputs. Off my head, handling this would require a convention across all languages for how to perform modulo or an enumerated type of modulo where all languages perform the operation according to the mathematical rules specified in the message.

**Comment by EpsilonPrime** [comment]
We have been adding options to describe the behavior for corner cases (such as division by zero).  We can add those here.

**Comment by EpsilonPrime** [comment]
Addressed by #583.  Thanks @jordanvieler !
