### ISSUE TITLE
Looks like you've added a CLA requirement, can you please provide a Corporate CLA?

### ISSUE THREAD

**Issue by jkmarz** [substrait-io/substrait#355]
Hi! At our company, individual developers are not permitted to bind the company to any agreement by GitHub-signing an online Individual CLA --- we need to execute a **Corporate** CLA that gets stamped by our legal department and signed by an officer of the company. Can you please provide a PDF of a **CCLA** that I can take through our process and then return to you? We have a number of folks who would like to contribute to Substrait.

Thanks!

**Comment by jacques-n** [comment]
Hi @jkmarz , welcome to the community. You're our first requestor for a CCLA so give us a moment and we'll get something shared. Thanks for your patience!

**Comment by jacques-n** [comment]
Please find a [CCLA here](https://drive.google.com/file/d/1emUB1j4CVGZqI42cve0UTGfpnpiaDK37/view?usp=share_link).

Primarily taken from [the ASF](https://www.apache.org/licenses/cla-corporate.txt), for your reference.

Sorry it took so long!

**Comment by jacques-n** [comment]
Ping @jkmarz

**Comment by jkmarz** [comment]
Thank you so much! (apologies, I have been out ill) Will get this reviewed w/ Legal ASAP.

**Comment by gforsyth** [comment]
Closing this since there is now an available CCLA.
