### ISSUE TITLE
LATERAL joins/CROSS APPLY

### ISSUE THREAD

**Issue by GavinRay97** [substrait-io/substrait#356]
Following discussion from community meeting, I figured I would share a usecase/example code for multiple engines in the event it's helpful.

The semantics of `LATERAL`/`CROSS APPLY` are approximately equivalent to a `for_each` loop.
IE, you might write:

```py
for artist in artists where <cond>:
   for track in artist.tracks where ... limit 2:
      for sale in track.record_sales where ... limit 3:
```

The subquery/function on the RHS is evaluated for each row in the LHS, and can reference the values in the LHS.
A correlated subquery with `for_each` semantics basically.

The equivalent representation of above pseudo-code would be:

- Postgres

```sql
SELECT ... FROM artist
	/* CROSS JOIN */ LATERAL (SELECT ... FROM track WHERE track.artist_id = artist.id LIMIT 2) track
	/* CROSS JOIN */ LATERAL (SELECT ... FROM record_sale WHERE record_sale.track_id = track.id LIMIT 3) record_sale
```

- Oracle

```sql
SELECT ... FROM artist
    -- These produce equivalent results
	CROSS APPLY (SELECT ... FROM track WHERE track.artist_id = artist.id LIMIT 2) track
	CROSS JOIN LATERAL (SELECT ... FROM record_sale WHERE record_sale.track_id = track.id LIMIT 3) record_sale
```

- SQL Server

I believe it uses `CROSS APPLY` keyword

---

You can emulate `LATERAL` + `LIMIT/OFFSET` in dialects that lack it using `row_number()` and partitioning by the join key:
```sql
-- This might not be entirely right but you get the idea
SELECT ... FROM artist
    JOIN (
        SELECT * FROM (
            SELECT *, ROW_NUMBER() OVER (PARTITION BY artist_id) AS row_number FROM track
        ) track
        WHERE row_number <= 2
    ) track ON track.artist_id = artist.id
    JOIN (
        SELECT * FROM (
            SELECT *, ROW_NUMBER() OVER (PARTITION BY track_id) AS row_number FROM record_sale
        ) record_sale
        WHERE row_number <= 3
    ) record_sale ON record_sale.track_id = track.id
```

CockroachDB for example implements `LATERAL` as a sugar on top of this:

```
> explain select * from abc, lateral (select * from xyz where x = a limit 2);
                                           info
-------------------------------------------------------------------------------------------
  distribution: local
  vectorized: true

  • filter
  │ estimated row count: 1
  │ filter: row_num <= 2
  │
  └── • window
      │ estimated row count: 2
      │
      └── • hash join
          │ estimated row count: 2
          │ equality: (x) = (a)
          │
          ├── • scan
          │     estimated row count: 6 (100% of the table; stats collected 2 minutes ago)
          │     table: xyz@xyz_pkey
          │     spans: FULL SCAN
          │
          └── • scan
                estimated row count: 1 (100% of the table; stats collected 3 minutes ago)
                table: abc@abc_pkey
                spans: FULL SCAN
```

**Comment by jacques-n** [comment]
How is this related to #357 ? Maybe we can consolidate?

**Comment by GavinRay97** [comment]
Ah these are the same thing, yes, I can close mine if you like

**Comment by curino** [comment]
@GavinRay97  and @ashvina can you please pick one of #356 and #357 and coordinate on this?

**Comment by ashvina** [comment]
Both issues have useful details. I agree, it makes sense to consolidate if any information is not lost.
What is the recommended resolution in such cases, it can repeat in future?

For context, I introduced the missing feature in the community sync meeting and created 357 as agreed in the meeting. I am also actively working on a fix (have created one PR and one more is WIP).
Ordering wise, 356 was created before 357.
