### ISSUE TITLE
Questions about nullability and literal values 

### ISSUE THREAD

**Issue by jcrist** [substrait-io/substrait#358]
From reading the protobuf [spec](https://github.com/substrait-io/substrait/blob/main/proto/substrait/algebra.proto#L530), I see that a `Literal` node consists of:

- A type-specific oneof, one option of which is `Type null`
- A boolean `nullable` field indicating the values nullability

This leads to a few questions:

- When would you ever set `nullable=True`? If you know the literal value when generating the substrait isn't `NULL`, wouldn't you know the literal isn't nullable?
- If you have a literal `NULL` value, do you need to know the type of fields it's being used with to properly generate the `Literal` node (to fill in the `Type null` bit)?

To put things more concretely, given an `i64` field `x`, how would you represent:

1. The literal `1` in the expression `x == 1`?

I'd guess it'd be a `Literal(i64=1, nullable=False)`? When would you set `nullable=True`?

2. The literal `null` in the expression `x == null` (or some similar expression with a literal `null`).

Since `x` is an `i64` column, should that be `Literal(null=Type(i64=I64(nullability=NULLABILITY_NULLABLE)))`?

---

*Apologies if my terminology above is incorrect/doesn't make sense, I'm very new to this project*

**Comment by jacques-n** [comment]
> When would you ever set nullable=True? If you know the literal value when generating the substrait isn't NULL, wouldn't you know the literal isn't nullable?

In some ways your question is similar to "Why would I ever say literal 1 with i64 since it would fit in i8?". The intention of a the null literal is that you should be able to express the full definition of the type associated with a literal. This is useful in several scenarios. A couple of examples:
* My system doesn't support non-nullable values. In this situation, I need all my literals to be nullable.
* I want to use a null in a CTAS and want to make sure the output types are consistent with a particular pattern.

> If you have a literal NULL value, do you need to know the type of fields it's being used with to properly generate the Literal node (to fill in the Type null bit)?

In the Substrait model, all values (literal or references) have an associated. This allows things like validating which function bindings are allowed. As such, a null value should also be typed. This is similar to the pattern that Substrait doesn't generally support implicit casts. The producer of a Substrait plan needs to declare explicit casts/coercisions to create a correctly bound plan. (For example, `sign(i64)` doesn't support accepting an `i8` argument.)

**Comment by jcrist** [comment]
Thanks for the reply, this is very helpful.

> My system doesn't support non-nullable values. In this situation, I need all my literals to be nullable.

Wouldn't cases like this lead to dialects of substrait, where a query written for one system (which requires nullable literals) wouldn't work on another system (which forbids them)? Does that go against the intentions for this project? Do we expect cases like this to be common in practice, or just temporary shortcomings (and in the long run all systems should accept all forms)?

This makes it tricky for systems like [ibis](https://github.com/ibis-project/ibis-substrait), where we'd have to know what restrictions the backend has before generating substrait for a given expression. Acero for example currently only allows non-nullable literals.

**Comment by westonpace** [comment]
FWIW, we should loosen this restriction in Acero.  In the initial draft of the consumer we rejected anything that we couldn't round trip through Acero.  Since an Acero literal is an Arrow scalar and an Arrow scalar is a "value + type" and a type does not contain nullability we have no way of round-tripping the information.

From a dumb (e.g. no optimization) consumer perspective, this field is pretty much meaningless (if the literal is not null it's not nullable.  If it is null then it's nullable).

In general, if a consumer has no notion of literal nullability then I would expect it to ignore the field and not reject based on a certain value.  I think Acero was being overly strict here.

Acero behaves similarly with hints.  If there are any hints present it rejects them.  This isn't necessarily a sign that hints are bad but more that Acero can't round trip them and is being overly strict at the moment.

**Comment by westonpace** [comment]
> My system doesn't support non-nullable values. In this situation, I need all my literals to be nullable.

I don't buy this argument.  If a literal didn't contain nullability information then your system wouldn't interpret the literal as non-nullable.

> I want to use a null in a CTAS and want to make sure the output types are consistent with a particular pattern.

This is perhaps more compelling, though feels a little corner-casey.

However, I'd go with a simpler argument:

 * A literal is an expression.  All expressions have a type and a nullability.  For consistencies sake therefore a literal also has a nullability.

**Comment by jcrist** [comment]
To rephrase my remaining question/issue:

- We'd like to generate substrait from an ibis expression that can be consumed by all consumers
- That substrait will likely contain `Literal` expressions
- For literals whose values aren't `NULL` (e.g. `1`), is there a consistent value we can set `nullable` to that should work for all backends?
 
Previously we defaulted to `nullable=True`, which didn't work for acero (even if that may be fixed in acero later). We're now defaulting to `nullable=False`. Is that likely to run into problems with a different system?

**Comment by jcrist** [comment]
Thanks Weston, that solves our immediate problem.

But now I'm curious - if you're saying "consumers should accept literals with either `nullable=False` or `nullable=True`", then doesn't that make the `nullable` flag kinda meaningless? What behavior would change for an integer literal with `nullable=True` vs `nullable=False` for an engine that cared about these concepts? Why have the flag at all?

**Comment by westonpace** [comment]
I think it is valid (and there is precedent) for a consumer to consider nullability to be a property of fields and not a property of types/expressions.  This is what Arrow does (it's not just an Acero thing).  This appears to be what postgres does (though without looking at the source I can't really tell) judging by the fact that columns from CTAS are always nullable.  There are plenty of programming languages that have no concept of "nullable expressions" (e.g. C++, Java).  In this case the consumer should ignore the flag.

There is precedent for programming languages that consider nullability to be a property of expressions.  For example, in C# this will fail to compile `var x = 7; x = null;`.  Meanwhile this will succeed, `var x = (int?) 7; x = null;`.  I think SQL server works this way as evidenced by [this article](https://social.msdn.microsoft.com/Forums/en-US/7af9edf4-9b26-4a00-b14a-8a6263f22675/nullable-fields-when-using-selectinto?forum=transactsql).

If a consumer falls into the former category then it should completely ignore the field.  If a consumer falls into the latter category then it should support both options.

**Comment by westonpace** [comment]
Although, if we accept that some systems may validly ignore the nullability of expressions, then statements like CTAS become a problem.  We will need some kind of flag / option to control whether or not the producer needs the columns to have expression-based-nullability or whether it doesn't care.

**Comment by jacques-n** [comment]
> A literal is an expression. All expressions have a type and a nullability. For consistency's sake therefore a literal also has a nullability.

This is definitely true. I thought it was clear so didn't state it. I was trying to give examples of use cases where this might be considered.

The reality I've seen is most systems look at expressions the same whether they are literals or not. While there are some special cases such as SQL servers apparent smart literal decimal handling, that's not the common case. There are numerous common cases where one is mixing literals and non-literals and wants those to expose consistent type nullability. One common use of literals is virtual tables. In these situations, imagine I have a virtual table like 

```select * from VALUES (1,null,'hello'), (5,2,'bye') AS T(a,b,c);```

In this situation, in Substrait, the data type of b should clearly be a nullable type. I should be able to validate each individual value for b and confirm that it has a consistent expression type with the parent field type. As such, the 2 in the second row of the dataset in column be should be declared as nullable, even though in that particular cell it is not null.

> We will need some kind of flag / option to control whether or not the producer needs the columns to have expression-based-nullability or whether it doesn't care.

I have been thinking about this problem differently (maybe?). If some consumers don't support a particular format, we should produce a shared set of rewrite rules that change the plan (some lossless, some lossy). For example, if a system doesn't support non-nullable types, we could have a rule that rewrites the entire plan to nullable types. I wouldn't solve this at individual locations, rather solve as a common pattern of transformations.

**Comment by westonpace** [comment]
> For example, if a system doesn't support non-nullable types, we could have a rule that rewrites the entire plan to nullable types

I wouldn't phrase it as "system doesn't support non-nullable types" as I think that is an different problem.  Instead I would phrase it as "system doesn't consider nullability to be part of an expression".

I'm not sure rewrite rules are needed as it doesn't matter whether you rewrite the literals to nullable or non-nullable the system is going to consume the plan the same way.

**Comment by westonpace** [comment]
I think there was some good discussion here but I'm not sure if we arrived at anything actionable and it appears the discussion has gone stale.  I am going to close this.
