### ISSUE TITLE
Member names of the Version message conflict with some macros

### ISSUE THREAD

**Issue by bkietz** [substrait-io/substrait#361]
For some compilers/C library combinations, the generated accessors `Version::major()` etc collide with a definition in `<sys/sysmacros.h>`

> /home/bkietz/arrow/cpp/debug-build/substrait_ep-generated/substrait/plan.pb.h:850:12: warning: In the GNU C Library, "major" is defined by <sys/sysmacros.h>. For historical compatibility, it is currently defined by <sys/types.h> as well, but we plan to remove this soon. To use "major", include <sys/sysmacros.h> directly. If you did not intend to use a system-defined macro "major", you should undefine it after including <sys/types.h>. [-W#pragma-messages]

This warning arose while compiling `plan.pb.cc`, so unfortunately the fix isn't as simple as an `#undef` before including generated code.

For projects whose CI builds with -Werror (all warnings are errors), this is problematic. Simply suppressing the warning will not work since the C preprocessor will replace instances of `major` with calls to the macro. Could those accessors could be renamed to `major_` and `minor_`?

**Comment by westonpace** [comment]
Closed by #362
