### ISSUE TITLE
Should we add a "union field" reference segment?

### ISSUE THREAD

**Issue by westonpace** [substrait-io/substrait#369]
Arrow has something like this.  Given a `my_union:union<i32,i64>` and a reference `my_union[0]` it would return an `i32` array with nulls inserted where the union value was not `i32`.

Do we want this in Substrait?

**Comment by jacques-n** [comment]
I feel like most systems that more and more modern systems are veering away from support of unions as a type. Struct in Substrait provides the same properties asfaict. For historical reference, @cpcloud and I both consciously agreed to exclude it in the original design. I'd suggest that if you need it, introduce using extension types.

What do others think?

**Comment by jacques-n** [comment]
I feel like most systems that more and more modern systems are veering away from support of unions as a type. Struct in Substrait provides the same properties asfaict. For historical reference, @cpcloud and I both consciously agreed to exclude it in the original design. I'd suggest that if you need it, introduce using extension types.

What do others think?

---

Rereading your question I'm wondering if your asking for some variation of coalesce as opposed to an actual union data type. Is there a reason a function is insufficient?

**Comment by westonpace** [comment]
For some reason I thought `union` was a canonical type.  Given that it isn't, I agree there is no need for this.  Yes, this could be achieved without unions using multiple columns and coalesce.
