### ISSUE TITLE
Add "Powered by Substrait" page to website

### ISSUE THREAD

**Issue by ianmcook** [substrait-io/substrait#394]
In the 2022-11-23 sync meeting, we discussed the need for a public list of third-party projects that have implemented Substrait integrations.

One way to achieve this would be to add a "Powered by Substrait" page to the website, similar to the Apache Arrow project's [Powered by page](https://arrow.apache.org/powered_by/). I'll take a stab at creating this.

**Comment by MasseGuillaume** [comment]
It's possible to find open sources users via their respective repositories:

go-lang: https://pkg.go.dev/github.com/substrait-io/substrait-go?tab=importedby
Java: https://central.sonatype.dev/artifact/io.substrait/core/0.2.0/dependents
rust: https://crates.io/crates/substrait/reverse_dependencies
C#: https://www.nuget.org/packages?q=substrait (Not yet released, should be available via [used-by](https://www.nuget.org/packages/Microsoft.Spark#usedby-body-tab))
Ruby: https://rubygems.org/search?query=substrait (Not yet released, should be available via [reverse_dependencies](https://rubygems.org/gems/json/reverse_dependencies))

Currently, it's empty.
