### ISSUE TITLE
Build on (or take inspiration from) MLIR?

### ISSUE THREAD

**Issue by h-vetinari** [substrait-io/substrait#41]
I just saw the [announcement](https://mail-archives.apache.org/mod_mbox/arrow-dev/202109.mbox/%3cCAJPUwMCr5pO_-t-1YpFbP2HNkKi8sHA3b1ZMdbWQ1BnzOwueGA@mail.gmail.com%3e) email on the arrow mailing list. I read the [project vision](https://substrait.io/), and I understand "Why not use SQL?" & "Why not just do this within an existing OSS project?". 

But I was wondering if relation to / compatibility with [MLIR](https://mlir.llvm.org/) was considered at all already (which is license-compatible with arrow)? I can understand the desire to start a-fresh, and MLIR is probably also overkill in many ways, but I was thinking that if the IR is designed in an MLIR-compatible way from the start, it might unlock unexpected future benefits, like being able to leverage all the compiler-optimizations available in LLVM.

A quick google search [showed](https://mboehm7.github.io/resources/AMLS_DAPHNE_projects.pdf) that someone (CC @mboehm7) already had a similar idea.

**Comment by jacques-n** [comment]
Hey @h-vetinari , thanks for dropping by. Best I can tell, MLIR is generally much lower level/broader than what we're trying to achieve in Substrait. The Daphne example is also a superset of what we're after here (it seems to be partialsql > relational algebra > mlir). Substrait only deals in the relational algebra level, with the goal being that other mature technology can work with Substrait to better connect those systems. 

Given the differences in levels of abstraction, I would be highly surprised if our proposal isn't amenable to translation to MLIR. Have you take a look of what we've sketched out to evaluate this?

**Comment by h-vetinari** [comment]
Hey @jacques-n, thanks for the quick response. I can see that it wouldn't be the first priority for substrait, but I can imagine a future where such an IR could be processed by many more tools, hence this question. As long as it's been considered at some point, that's already a good start.

> Have you take a look of what we've sketched out to evaluate this?

I've had a look at the project page, but TBH I also don't know MLIR nearly well enough to say how this would/could be mapped.

**Comment by cpcloud** [comment]
Closing this out. Thanks all. Please open a GitHub discussion if you'd like to discuss further.
