### ISSUE TITLE
Question / request for Project operation

### ISSUE THREAD

**Issue by mbasmanova** [substrait-io/substrait#43]
> The project operation will produce one or more additional expressions based on the inputs of the dataset.

Would it be possible to allow project operation to optionally drop columns, e.g. have it defined as adding zero or more expressions and dropping zero or more columns?

**Comment by jacques-n** [comment]
[Emit remapping](https://substrait.io/relations/basics/#emit-output-ordering) functionality applies to all operations (including project). Emit allows any operation to reorder or drop columns (or use a default output ordering). Will try to post an update of proto for basic sketch of all the common relational operations this weekend. Thanks!

**Comment by mbasmanova** [comment]
Make sense. A follow-up question:

> Note that remapping/exclusion can only be done at the outputs root struct.

What does this mean?

**Comment by jacques-n** [comment]
> Make sense. A follow-up question:
> 
> > Note that remapping/exclusion can only be done at the outputs root struct.
> 
> What does this mean?

It means that you can't use the generic mapping system to reorder/rename inner columns. You'd need to you a special function (or we may need to introduce another expression type, an projecting version of the "Masked Complex Expression".
