### ISSUE TITLE
Confused section for expressions arguments

### ISSUE THREAD

**Issue by Aitozi** [substrait-io/substrait#433]
In [link](https://github.com/substrait-io/substrait/blob/07e4feb5983478e7d0d95dc1d9b5e176685dbdc3/site/docs/tutorial/sql_to_substrait.md?plain=1#L359) 

> `arguments` defines the arguments being passed into the function, which are all
done positionally based on the function definition in the YAML file. The first 
argument is an option that defines how `NaN` equality is handled, and since
that's not relevant here we just pass `"NAN_IS_NOT_NAN"`. The next two options
will be familiar as the literal and the field reference we constructed earlier.

I do not see the argument for the `how NaN equality is handled` in the `INDEX_IN` and `IS NULL`, nor the `NAN_IS_NOT_NAN`. Do I miss something?

**Comment by westonpace** [comment]
Ah, that is out of date.  You are not missing anything.  Options are now optional and if they are specified the format is a little different.  The plan is correct if the user does not care how NaN equality is handled.  If the user really wanted NAN_IS_NOT_NAN they could do:

```
,
            "arguments": [
              {
                "value": {
                  "literal": {
                    "string": "Computers"
                  }
                }
              },
              {
                "value": {
                  "selection": {
                    "directReference": {
                      "structField": {
                        "field": 1
                      }
                    },
                    "rootReference": {}
                  }
                }
              }
            ]
            "options": {
              "nan_equality": "NAN_IS_NOT_NAN"
            }

**Comment by westonpace** [comment]
CC @wjones127 did you want to fix this?

**Comment by Aitozi** [comment]
@westonpace Get it, thanks for your explanation
