### ISSUE TITLE
Question / request for Join operation

### ISSUE THREAD

**Issue by mbasmanova** [substrait-io/substrait#44]
The join operation currently support inner, outer, left and right joins. I believe it also supports a cross join by allowing literal True for the join expression. I wonder how semi and anti joins are supported?

**Comment by jacques-n** [comment]
Good questions. Yeah, literal true supports cross joins (and would transform into the proposed NLJ). For semi, anti-joins and correlations, I have several notes but have been torn on how to express. Do you want to take a pass on proposing some updates to the relational spec pages to try to tease these out?

**Comment by jacques-n** [comment]
Hey @mbasmanova , I posted patch to add join proto in #46

**Comment by mbasmanova** [comment]
@jacques-n Sound good. I have somewhat limited bandwidth, but will checkout #46 and try to come up with a proposal for th above.

**Comment by cpcloud** [comment]
We have joins now! Thanks @mbasmanova.

**Comment by mbasmanova** [comment]
Nice. @rui-mo Rui, should we add Substrait-to-Velox conversions for joins?

**Comment by marin-ma** [comment]
@mbasmanova We've already added hash-join conversion for internal use, and we're planning to upstream.
