### ISSUE TITLE
Visualization tools for substrait

### ISSUE THREAD

**Issue by eedalong** [substrait-io/substrait#444]
Any visualization tools for substrai?

**Comment by mbrobbel** [comment]
The [validator](https://github.com/substrait-io/substrait-validator) can generate HTML reports for queries with a detailed overview of the plan including the relation graph. To get an idea you can quickly try this [here](https://mbrobbel.github.io/substrait-validator/), but please note that this demo is based on an old version of the validator, and I would recommend [installing the validator](https://github.com/substrait-io/substrait-validator#command-line-interface).

**Comment by westonpace** [comment]
I think this question has been answered (to the extent that it can be) so I will close this.  If there is a specific request for a specific visualization or tool then feel free to open a new issue.
