### ISSUE TITLE
Add `regexp_match_substring_all` function

### ISSUE THREAD

**Issue by ianmcook** [substrait-io/substrait#466]
The Substrait functions YAML defines the function `regexp_match_substring` which returns a scalar string value containing a single occurrence of the matched substring. Many systems implement this function. Those systems often name it `regexp_extract`.

Some systems also implement a variation of this function that extracts an array/list of _all_ the matched substrings. For example [Presto](https://prestodb.io/docs/current/functions/regexp.html) and [Spark](https://spark.apache.org/docs/latest/api/sql/index.html#regexp_extract_all) both implement `regexp_extract_all`. We should define a function `regexp_match_substring_all` in the Substrait functions YAML that we can map onto these.

**Comment by richtia** [comment]
> @pdet @cpcloud @westonpace @richtia

I can work on adding this.

**Comment by westonpace** [comment]
> We should define a function regexp_match_substring_all in the Substrait functions YAML that we can map onto these.

Do you mean `regexp_extract_all`?

**Comment by ianmcook** [comment]
> Do you mean `regexp_extract_all`?

The function that is named `regexp_extract` in many SQL systems is named [`regexp_match_substring`](https://github.com/substrait-io/substrait/blob/7d7ddf11f3ce0b5f69a9d32ef10a699888f18a61/extensions/functions_string.yaml#L80) in Substrait.

So following that naming convention, `regexp_extract_all` would be named `regexp_match_substring_all` in Substrait, I think?

**Comment by westonpace** [comment]
Thanks for the clarification. I agree.
