### ISSUE TITLE
Add FAQ on how substrait relates to Beam's work on relational modelling?

### ISSUE THREAD

**Issue by emkornfield** [substrait-io/substrait#47]
[A reply to the announcement on the BEAM dev mailing list](https://lists.apache.org/thread.html/r6112e3c28cd6759867c3bc37b546c0d8183f9431c6dbe234d3af018f%40%3Cdev.calcite.apache.org%3E) had some substantive questions buried in it.  It might pay to write up something as to what differences/overlap substrait is with Beam's efforts.

**Comment by jacques-n** [comment]
Bonkers, I'm subscribed to that list and watched that thread and never saw that message come through. Will reply there for sure with at least my thoughts. @emkornfield do you want to take a shot at this ticket?

**Comment by emkornfield** [comment]
I can opine on some of them, but in terms of the technical issues, I might not be the best person to give a full answer (I have some familiar with ZetaSQL but practically not with Beam and I have not had the time to really get through the current proposal here).   So I can take a first pass and invite them over if they want to discuss more.

**Comment by jacques-n** [comment]
I responded on the mailing list. Thanks @TheNeuralBit for mentioning!

**Comment by emkornfield** [comment]
Seems like the rest can hopefully be worked out either in discussion there or here.  Going to close.
