### ISSUE TITLE
Add weblink & tags to repo

### ISSUE THREAD

**Issue by universalmind303** [substrait-io/substrait#471]
Most repos link their webpage & add tags in the "About" section. Substrait should do the same. 

Examples: 
![image](https://user-images.githubusercontent.com/21327470/224355143-ffbef334-c94e-46b3-8f79-bdd37bea93d2.png)
![image](https://user-images.githubusercontent.com/21327470/224355220-f68a793c-9d67-419e-a9cf-d36b9703a124.png)

**Comment by westonpace** [comment]
I made an initial stab at this, feel free to reopen with more suggestions of tags:

![image](https://user-images.githubusercontent.com/1696093/225082300-fd53ba65-f0d9-4243-b3f1-abb1a3b80c83.png)

**Comment by westonpace** [comment]
And thanks for the suggestion!
