### ISSUE TITLE
Add option to control whether day/week/month/quarter from `extract` is  0- or 1-indexed

### ISSUE THREAD

**Issue by ianmcook** [substrait-io/substrait#477]
[This discussion in the DuckDB repo](https://github.com/duckdb/duckdb/issues/6805#issuecomment-1479542817) suggests that we should consider adding an option to the Substrait [`extract` datetime function](https://github.com/substrait-io/substrait/blob/b7df38d2099cd970d1ed1783d441d828ce84253d/extensions/functions_datetime.yaml#L5) to allow Substrait producers to specify whether they expect returned day/week/month/quarter integer values to be 0- or 1-indexed.

**Comment by ianmcook** [comment]
@rok do you have any thoughts about this?

**Comment by rok** [comment]
I suppose this is down to API design. Do we want to:
1. Add an extra parameter to extract
2. Add new extract components
3. Keep a minimal set of functions (as is) and force users to do some glue-ing

**Comment by rok** [comment]
I assumed 3. is preferred, but if that's not the case I'd prefer 1 and can make a PR.

There are two more candidates for such a change: `YEAR/ISO_YEAR/US_YEAR`, `MONDAY_WEEK/SUNDAY_WEEK/ISO_WEEK/US_WEEK`.

**Comment by ianmcook** [comment]
I don't think this affects `YEAR`, `ISO_YEAR`, or `US_YEAR` because year integers are not indices in the same sense.

**Comment by rok** [comment]
It's not about indexing indeed :D, but we could collapse three extract functions if we added parameters.

**Comment by westonpace** [comment]
For indexing let's make it an option (not an argument).

Let's defer calendar type for a future PR since it's backwards incompatible.  I think I'd want to see at least one non-arrow engine and how they chose to implement the feature first.

**Comment by ianmcook** [comment]
Closed by https://github.com/substrait-io/substrait/pull/479
