### ISSUE TITLE
Question: How to convert an function expression to substrait IR

### ISSUE THREAD

**Issue by yma11** [substrait-io/substrait#50]
Hi @jacques-n,
As defined in [function.proto](https://github.com/substrait-io/substrait/blob/main/binary/function.proto), each function has a property "Extensions.FuntionId" which should be mapped with a unique implementation of a specific function and also a "Implementation" location. So the implementation will be available in the Implementation:uri, right? So when converting a plan to substrait IR, will the workflow be like following？
1) analyze expressions of the PlanNode, such gt(<int32>a, 8) and validate its implementation status by retrieving info from Implemention:uri, by returning an Extensions.FunctionId?
2) fulfill other fields of the expression, like fieldReference "a", constant "8" and its output_type "boolean".
3) Is there a missing on the Op name "gt" in the Expression:ScalarFunction? like it should be 
    message ScalarFunction {
        Extensions.FunctionId id = 1;
        string name = 2;
        repeated Expression args = 3;
        Type output_type = 4;
    }

I would like to try converting presto physical plan into substrait IR, is there more info I can refer? 
Thanks.

**Comment by jacques-n** [comment]
I'm working an example but in the meantime. We definitely need to improve the docs/etc. (Patches are welcome :).

The model is:
- A [plan](https://github.com/substrait-io/substrait/blob/main/binary/plan.proto#L13) has a set of extensions. 
- Each extension has a type and git uri location. The uri location has a list of functions You can see an example scalar function listing [here](https://github.com/substrait-io/substrait/blob/main/extensions/scalar_functions.yaml).
- A plan also has a list of [mappings](https://github.com/substrait-io/substrait/blob/main/binary/extensions.proto#L32). A [function mapping](https://github.com/substrait-io/substrait/blob/main/binary/extensions.proto#L45) maps a specific function instance from the list of functions in the function list to a function id. This is done by indexing using the name followed by the subindex if there are multiple variations of the function with the same name.  
- An expression tree uses the scalar function expression to use an instance of the function with the functionid defined in the function mapping.

FunctionId and ExtensionId are arbitrary in the plan are simply ids to create a relationship within the normalized structure. 

For reference: 
- In `Extension`, id is a primary key for use elsewhere.
- In `FunctionMapping`, the ExtensionId is a foreign key pointing at the extension declared in `Extension`
- In `FunctionMapping`, the FunctionId is a primary key.
- In `ScalarFunction`, the FunctionId points at the primary key defined in `FunctionMapping`

Let me know if that makes sense.

**Comment by yma11** [comment]
@jacques-n Thanks for your detailed explanation!  So I can see that once function instance to be used is determined, it will have name property. I have further question about the logic to determine which function instance should be used.  By matching the Op name/input type/output type info from PlanNode against functions descriptions in the function yaml as you mentioned? Shouldn't functionId also be included in the yaml file for each function? Or how is it generated?

> * An expression tree uses the scalar function expression to use an instance of the function with the functionid defined in the function mapping.
By the way, how to determine the index value Take [add](https://github.com/substrait-io/substrait/blob/main/extensions/scalar_functions.yaml#:~:text=scalar_functions%3A,return%3A%20T) for example, when the function is add(20211010 + 3days], the index will be 2?

**Comment by jacques-n** [comment]
> ...logic to determine which function instance should be used

There will need to be some kind of manual mapping to map internal function ids (say in Presto) to the definition in a particular Yaml. You'll need to map type handling and semantics. Ultimately, to help with this I'd like to add test cases to the substrait project that help one to validate that semantics, etc are consistent.

> how to determine the index value Take add for example, when the function is add(20211010 + 3days], the index will be 2?

Yup, that is the current pattern. I'm open to alternatives. Having people manually manage functional ids in a yaml seems more complex and coupled with little additional benefits. What do you think?

**Comment by jacques-n** [comment]
I think you're talking about two different things: execution function resolution and semantic resolution. Let's try to keep them separate. I agree that add(i8,i8) and add(i16,i16) are one semantic definition with a bounded type variable `K` in Substrait whereas in most execution systems they are two separate execution functions. 

Part of the goal with the Substrait semantic definitions was to keep things DRY since they will need humans to maintain them (at least in part). I did contemplate having an individual set of bounds indexes as part of functionId when expressing an actual expression tree. For example, functionid would actually be something akin to: `add[0][K:i8]`. However, that is actually duplicative information when used in the context of of an actual [scalar binding](https://github.com/substrait-io/substrait/blob/main/binary/expression.proto#L84) since all expressions already have well defined output type information.

Any additional thoughts @cpcloud and @westonpace ?

**Comment by jacques-n** [comment]
I believe we have pretty good contact on this now. We've updated the documentation and serialization names to help clarify the concepts. Closing for now. Reopen if you feel like something is missing.

Thanks!
