### ISSUE TITLE
Question: Should we cover some distributed communication operators?

### ISSUE THREAD

**Issue by winningsix** [substrait-io/substrait#56]
I am not sure whether Substrait should provide communication operators like shuffle/exchange relations? It's more around how Substrait is used for distributed execution backend.

**Comment by jacques-n** [comment]
We do have several operations in the specification including:

- [Distribute Operator](https://substrait.io/relations/physical_relations/#distribute-operator)
- [Merging Capture](https://substrait.io/relations/physical_relations/#merging-capture)
- [Simple Capture](https://substrait.io/relations/physical_relations/#simple-capture)

We also expose the concept of [Distribution Property](https://substrait.io/relations/basics/#distribution). Is there something specific that you're not finding?

Note that these have yet to be added to the proto definitions so if you'd like to pull together a patch, that would be great!

**Comment by winningsix** [comment]
Oh, that works. Sorry, I only looked into binary. We will have a check on that. Thanks!
