### ISSUE TITLE
`substait-rs` build failed: protoc failed: substrait/algebra.proto:166:18: Explicit 'optional' labels are disallowed in the Proto3 syntax. 

### ISSUE THREAD

**Issue by zhangxffff** [substrait-io/substrait#710]
I encounter this failed while I build `arrow-datafusion`, which has dependency on `substrait-rs`.
![image](https://github.com/user-attachments/assets/cd466d6e-f5f0-4d36-9bfe-a4c2b329a482)

It seems like recently change use optional in substrait/algebra.proto, which is disallowed in Proto3
https://github.com/substrait-io/substrait/commit/5a73281e14448a69d5cb38515cb1a79050eb54eb

**Comment by mbrobbel** [comment]
You may need to update your `protoc`, what version are you using? `optional` is supported in proto3: https://github.com/protocolbuffers/protobuf/blob/main/docs/field_presence.md#protoc-invocation since `3.12`.
