### ISSUE TITLE
Take over maintenance/accept donation of DuckDB substrait-extension

### ISSUE THREAD

**Issue by jacques-n** [substrait-io/substrait#731]
I believe that there will be little development moving forward on [Duckdb Substrait extension](https://github.com/duckdb/substrait) as a duckdb core extension. There have been no commits for a couple of months and the home page is fairly cool on accepting contributions "We do not have the capacity to engage with issues or pull requests from external contributors at present". 

Myself and a few others have started enhancing the extension [in a separate repo](https://github.com/sundeck-io/duckdb-substrait). However, we'd like to avoid having multiple active forks. I reached out to the DuckDB team to see if they would potentially be open to moving the main repo to the Substrait project so that we can continue it's development and growth. They've initially been receptive to this idea. I wanted to open discussion here to see whether others in the Substrait community are equally supportive of including accepting. Would love feedback from @substrait-io/smc as well as anyone else in the community. For example, I think @drin has also been [working on this extension](https://github.com/duckdb/substrait/pull/114).

**Comment by drin** [comment]
I would be happy to collaborate to make sure independent work is eventually coalesced somewhere (it seems a substrait repo would be likely).

I would like to clarify if the main goal is just to expand the number of users that can review and merge PRs by having the "primary" home be under substrait rather than duckdb?

**Comment by hannes** [comment]
DuckDB maintainer here, we are indeed happy with the idea of the `substrait` extension moving here.

**Comment by westonpace** [comment]
+1

Given the duckdb team is fine with transferring maintenance and you are comfortable with accepting maintenance I am having a hard time seeing any downsides.  There may be some hiccups / compatibility differences between the two as people switch but long term compatibility between the projects seems well worth it.  Thank you @jacques-n for taking this effort on.

**Comment by mbwhite** [comment]
+1 here; several months back I think I found a few things that needed tweaking.

**Comment by vbarua** [comment]
+1 from me as well. Would we want to set it up as a core repo, or a contrib repo?

**Comment by jacques-n** [comment]
> Would we want to set it up as a core repo, or a contrib repo?

Either seems fine. I'm slightly inclined to go with non-contrib repo since the main challenge contrib is solving is ensuring access for non-substrait committers. I think at least four people who will be contributing are already committers so using contrib is probably less needed.

**Comment by drin** [comment]
> the main challenge contrib is solving is ensuring access for non-substrait committers

Technical reason aside, I think it'd also be a bit weird to request to take ownership but then to call it a "contrib", so my preference would also be a core/standard repo

**Comment by jacques-n** [comment]
Seems like we have some positive energy here and 3 +1s from SMC (@westonpace , @vbarua , myself). Will leave open for another day or two for additional feedback before concluding. Would love feedback @EpsilonPrime and @cpcloud .

**Comment by EpsilonPrime** [comment]
As DuckDB is my favorite database and Substrait is my favorite
cross-language relational algebra serializer I'm in favor of this proposal.

**Comment by ianmcook** [comment]
+1 from me. Thank you!

**Comment by jacques-n** [comment]
Repo has been moved over. 🎉  Thanks to everyone, especially the DuckDB team and @hannes !

https://github.com/substrait-io/duckdb-substrait-extension
