### ISSUE TITLE
Types: Do decimal literals need to carry around their precision and scale?

### ISSUE THREAD

**Issue by cpcloud** [substrait-io/substrait#74]
It's not clear to me whether decimal literals should carry around their type.

I can imagine a trivial SQL query like `SELECT decimal('234.234')`, and it's not clear what the type of that expression would be.

Should decimal literals also carry around their precision and scale information?

**Comment by jacques-n** [comment]
Yes, they should. We need to update the decimal literal format.

**Comment by jacques-n** [comment]
Resolved by #85
