### ISSUE TITLE
Question: why are IfThen and SwitchExpression messages near exact copies of each other?

### ISSUE THREAD

**Issue by cpcloud** [substrait-io/substrait#91]
What is the use case for having `IfThen` and `SwitchExpression` messages that are effectively exact copies of each other?

```protobuf
  message IfThen {
    repeated IfClause ifs = 1;
    Expression else = 2;

    message IfClause {
      Expression if = 1;
      Expression then = 2;
    }
  }

  message SwitchExpression {
    repeated IfValue ifs = 1;
    Expression else = 2;

    message IfValue {
      Expression if = 1;
      Expression then = 2;
    }
  }
```

I understand the difference between the two different types of `CASE` expressions in SQL.

Can't we represent `SwitchExpression` in terms of an `IfThen` with an equality condition?

If we still need to distinguish between the two ... cases (pun intended), can we refactor this to use an `enum` for differentiating instead of two effectively identical constructs?

**Comment by jacques-n** [comment]
This seems like an oversight. I believe the if in ifvalue for switch expression should be a literal, not an expression.

**Comment by jacques-n** [comment]
> @jacques-n Is it valid to mix literals and expressions in a single `when` expression (not that it would necessarily make sense)
> 
> like this:
> 
> ```sql
> select
>     case x
>       when 1 then 2
>       when y == 2 then 3
>       else null
>     end
> ```

I think the main difference is in the ifthen case, the result of the clause has to be a boolean value. In the other case, it has to be the same type as the pivot variable. So I guess you're pattern would be possible if you adjusted x to be a boolean value (and thus would need to change when 1 to when true or when false). I think...
