### ISSUE TITLE
Format: allow arbitrary expressions for grouping keys in AggregateRel

### ISSUE THREAD

**Issue by cpcloud** [substrait-io/substrait#92]
Currently, `AggregateRel` requires its `grouping` field to reference all fields by name:

```protobuf
message AggregateRel {
  // ...
  repeated Grouping groupings = 3;
  repeated Measure measures = 4;
  // ...
  message Grouping { repeated int32 input_fields = 1; }
  // ...
}
```

This forces producers to insert a projection that contains:

1. all grouping expressions
2. the unfurled arguments of every aggregation function call

The second is extremely onerous for producers. Any tree-like producer will have to be able to reconsitute every aggregate expression.

This leads to a _huge_ difference in the amount of code needed for producing `AggregateRel`s versus that needed for producing every other `Rel` variant: https://github.com/cpcloud/ibis/blob/substrait/ibis/backends/substrait/compiler.py#L687-L771 and makes producer code for `AggregateRel`s extremely fragile.

To me, this suggests that the `AggregateRel` `grouping` keys are likely at the wrong level of abstraction for the goal of producing a would-be-logical-plan (I understand the line is blurry between logical and physical, perhaps we can call this a "level 0 plan"?).

I propose that we allow arbitrary expressions for grouping.

**Comment by jacques-n** [comment]
I don't understand point two. Can you expound how changing grouping inner field to expression affects point 2?

**Comment by cpcloud** [comment]
> I don't understand point two. Can you expound how changing grouping inner field to expression affects point 2?

Sure.

Any aggregate expressions containing existing references to the table on which the new projection occurs are invalid, and so these aggregates need to be reprojected.
